name: jupyterlab-deck-lint

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10,<3.11
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=8
  - jupyterlab >=3.4.8,<4
  - jupyterlab-fonts >=2.1.1
  - pip
  - python >=3.7,<3.11
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,<17
  # host app
  - ipywidgets >=8
  # build
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - black
  - isort
  - ssort
  - docformatter
  - robotframework-tidy >=3.3
  # linters
  - robotframework-robocop >=2.6
  - pyflakes
  ### environment-lint.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
