name: jupyterlab-deck-lint

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10,<3.13
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=3.5,<5.0.0a0
  - jupyterlab-fonts >=3.0.0
  - notebook >=6.5,<8.0.0a0
  - pip
  - python >=3.8,<3.13
  - python-dotenv
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=20,<21
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.9.0,<4.0.0
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - ssort
  - ruff
  - robotframework-tidy >=3.3
  # linters
  - robotframework-robocop >=2.6
  ### environment-lint.yml ###
  ### environment-robot.yml ###
  - robotframework >=6.1
  - robotframework-pabot
  # browser
  - firefox 115.*
  - geckodriver
  - robotframework-jupyterlibrary >=0.5.0
  - lxml
  ### environment-robot.yml ###
