name: jupyterlab-deck-base

channels:
  - conda-forge
  - nodefaults

dependencies:
  ### environment-base.yml ###
  - python >=3.10,<3.11
  - pip
  - doit-with-toml
  - jupyterlab >=3.4.8,<4
  - ipywidgets >=8
  ### environment-base.yml ###
