name: jupyterlab-deck-demo

channels:
  - conda-forge
  - nodefaults

dependencies:
  ### test-environment.yml ###
  # runtimes
  - nodejs >=16,<17
  - python >=3.10,<3.11
  # host app
  - jupyterlab >=3.4.8,<4
  - ipywidgets >=8
  # build
  - flit >=3.7.1
  - doit-with-toml
  - twine
  - pip
  # test
  - pytest-cov
  - pytest-html
  - robotframework-jupyterlibrary >=0.4.1
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  ### test-environment.yml ###
