#!/usr/bin/env bash
set -eux
source activate ${NB_PYTHON_PREFIX}
IN_BINDER=1 doit dev

mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp examples/overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
