dependencies:
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
