*** Settings ***
Documentation       Selectors defined in this repo... could be loaded from JSON?


*** Variables ***
${CSS_DECK_NOTEBOOK_BUTTON}     .jp-ToolbarButtonComponent\[data-command="deck:toggle"]
${CSS_DECK_VISIBLE}             .jp-deck-mod-visible
${CSS_DECK_ONSCREEN}            .jp-deck-mod-onscreen
${CSS_DECK_STOP}                [data-icon="deck:stop"]
${CSS_DECK_PRESENTING}          [data-jp-deck-mode="presenting"]
