name: jupyterlab-deck-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  # formatters
  - black
  - isort
  - ssort
  - docformatter
  - robotframework-robocop
  - robotframework-tidy
  # linters
  - pyflakes
  ### docs-environment.yml ###
  # demo
  - jupyterlab-myst
  - jupyterlab-webrtc-docprovider
  - jupyter-videochat
  # docs
  - docutils >=0.18
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autobuild
  - sphinx-copybutton
  - myst-nb
  # lite cruft
  - pkginfo
  - pip:
      - jupyterlite ==0.1.0b13
  ### docs-environment.yml ###
